app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import abort, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import home
from ..models import Site, SitePermission


@home.route('/')
def homepage():
    """
    Render homepage
    """

    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render dashboard template
    """

    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title='Dashboard')


@home.route('/sitedashboard')
@login_required
def site_dashboard():
    # for regular users only
    if current_user.is_admin:
        return redirect(url_for(admin_dashboard))

    # note - consider use of inner join below instead of for loop. i'm not sure how to implement with sqlalchemy though.

    auth_sites = SitePermission.query.filter_by(user_id=current_user.id).all()
    sites = []
    for auth_site in auth_sites:
        site = Site.query.filter_by(id=auth_site.site_id).first()
        sites.append(site)

    return render_template('admin/sites/user_sites.html', sites=sites, title='User Sites')

app/site/__init__.py
# app/site/__init__.py

from flask import Blueprint

site = Blueprint('site', __name__)

from . import views

app/site/views.py
# app/site/views.py

from flask import g, jsonify, render_template, request
from flask_login import current_user, login_required
import ast
import json
import os

from . import site
from ..models import Site

from ..static.python import format_data, print_docs, email_attachments, zip_docs, delete_folder, make_cardlist
from ..static.python.check_admin import check_admin
from ..static.python.check_permission import check_permission



# get requested site

@site.url_value_preprocessor
def get_site_name(endpoint, values):
    site_url_slug = values.pop('site_url_slug')
    query = Site.query.filter_by(site_url_slug=site_url_slug)
    g.site = query.first_or_404()


@site.route('/')
@login_required
def site_home():
    check_permission(g.site)

    site_url_slug = g.site.site_url_slug

    # calibrate site-specific paths: static, upload folder

    app_root = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path2model = os.path.join(app_root, 'static/custom_site_data', site_url_slug, 'static/tmp/model.txt')

    cardlist = make_cardlist.make_cardlist(path2model)
    return render_template('site/layout.html', cardlist=cardlist)


@site.route('/admin')
@login_required
def admin():
    check_admin()

    site_url_slug = g.site.site_url_slug

    currModel = {}

    # calibrate site-specific paths: static, upload folder

    app_root = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path2model = os.path.join(app_root, 'static/custom_site_data', site_url_slug, 'static/tmp/model.txt')

    with open(path2model) as model:
        currModel = json.load(model)

    return render_template('site/index.html', currModel=json.dumps(currModel))


@site.route('/submitdata/', methods=['GET', 'POST'])
def submit():
    site_url_slug = g.site.site_url_slug

    # calibrate site-specific paths: static, upload folder

    app_root = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path2static = os.path.join(app_root, 'static/custom_site_data', site_url_slug, 'static')
    path2documents = os.path.join(path2static, 'documents')

    # Store posted_data in variable card_dictionary

    card_dictionary = ast.literal_eval(request.form['submit_data'])

    if 'STUDENT_EMAIL' in card_dictionary:

        # Format data in card_dictionary
        card_dictionary = format_data.format_data(card_dictionary, path2documents)

        # Create draft documents from templates:
        print_docs.print2docs(card_dictionary, path2documents)

        # Zip folder containing draft documents
        zip_docs.zip2folder(card_dictionary, path2documents)

        # Email attachment to user
        email_attachments.send_emails(card_dictionary, path2documents)

        # Delete zip folder from documents
        delete_folder.delete_folder(card_dictionary, path2documents)

        # # Email a calendar invite to student and clinical instructor regarding client's next court date.
        # email_calendar.email_calendar(card_dictionary)

    return jsonify({})


@site.route('/savecurrmodel', methods=['GET', 'POST'])
def post_data():
    site_url_slug = g.site.site_url_slug

    currModel = {}
    currModel = json.loads(request.args.get("payload"))

    # calibrate site-specific paths: static, upload folder

    app_root = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path2static = os.path.join(app_root, 'static/custom_site_data', site_url_slug, 'static')

    with open(os.path.join(path2static, 'tmp/model.txt'), 'w') as write_file:
        json.dump(currModel, write_file, indent=4, sort_keys=True)
    return "OK"

@site.route('/loadtemplate', methods = ['GET'])
def loadtemplate():
    loadFileName = request.args.get("payload")
    loadTemplate = {}
    with open("/templates/jstemplates/" + loadFileName) as loadFile:
        loadTemplate = loadFile.readlines()
    return " ".join(loadTemplate), 200

def splititup(i):
    j = i.split('<div class="container">',1)[1]
    jj = j.split('<div class="col s12"')
    nlist = []
    for x in jj:
        nlist.append('<div class="col s12"'+x)
    for n in nlist:
        if n.find('VET_ID') != -1:
            import re
            n = re.sub('None', '', n)
            # print n
            return n

app/templates/site/buttons.html
<div class="row center">
    {% for button in card.card_buttons %}
        <button class="btn-large waves-effect waves-white"
                disabled
                name="{{ card.card_id }}_BUTTON"
                value="{{ card.card_buttons[button] }}"
                onclick="update_page(
                        '{{ card.card_id }}',
                        '{{ card.card_type }}',
                        '{{ card.card_buttons[button] }}');">
            {{ button }}
        </button>
    {% endfor %}
</div>

app/templates/site/card.html
<div class="col s12">
  <div class="card">
    <div class="card-content">

      <div class="editQuestionWrapper">
        <h3 class="card-title center-align js-editTitleText">Hello, what is your name?</h3>
        <input type="text" class="card-title center-align js-editTitleField" placeholder="Hello, what is your name?" pattern=".{0,64}"/>
      </div>

      <div class="input-field col s12">
        <div class="js-editIconOptions">
          <i id="selectedIcon" class="material-icons prefix js-editIconIcon">language</i>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">face</i></div>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">date_range</i></div>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">local_phone</i></div>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">mail_outline</i></div>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">attach_file</i></div>
          <div class="iconOption"><i class="material-icons prefix js-editIconIcon">attach_money</i></div>
        </div>
        <select class="js-editAnswerType">
          <option value="textfield">Text Field</option>
          <option value="fileupload">File Upload</option>
          <option value="none">None</option>
        </select>
      </div>

      <div class="row center js-buttonWrapper">

      </div>

    </div>
  </div>
</div>

app/templates/site/card_type.html
{# IN CASE OF SELECT #}
{% if card.card_type == "select"%}

    {% include "site/card_type_select.html" %}

{# IN CASE OF TEXTBOX #}
{% elif card.card_type == "textbox"%}

    {% include "site/card_type_textbox.html" %}

{# IN CASE OF SUBMIT #}
{% elif card.card_type == "submitted"%}

    {% include "site/submitted_card.html" %}

{% endif %}

app/templates/site/card_type_select.html
{# SELECT CARD #}
<div class="col s12" id="{{ card.card_id }}_CARD" style="display: None">
    <div class="card">
        <div class="card-content">
            <h4 class="card-title center-align">{{ card.card_text }}</h4>
            <h4 class="card-title center-align">{{ card.card_subtext }}</h4><br>
            {% include "site/buttons.html" %}
            <h4><i class="activator small material-icons">info_outline</i></h4>
        </div>
{#        {% include "help_box.html" %}#}
    </div>
</div>

app/templates/site/card_type_textbox.html
{# TEXTBOX CARD #}
<div class="col s12" id="{{ card.card_id }}_CARD" style="display: None">
    <div class="card">
        <div class="card-content">

            {# QUESTION #}
            <h3 class="card-title center-align">{{ card.card_text }}</h3>

            {# INPUT FIELD #}
            <div class="input-field col s12">
                <i class="material-icons prefix">{{ card.card_icon }}</i>
                <input
                        id="{{ card.card_id }}"
                        class="{{ card.card_class }}"
                        type="text"
                        pattern="{{ card.card_pattern }}"
                        onchange="enable_buttons(this)"
                        onkeyup="enable_buttons(this)"
                        data-auto_complete="{{ card.card_auto_complete }}"
                        data-auto_populate="{{ card.card_auto_populate }}"
                        onfocus="auto_populate(this)"
                        {% if card.card_icon == 'add_location' %}placeholder=""{% endif %}>

                <label  for="{{ card.card_id }}{{ card.card_type }}"
                        data-error="Unable to Validate Input"
                        data-success="Great!">{{ card.card_subtext }}</label>
            </div>

            {# BUTTONS #}
            {% include "site/buttons.html" %}

            {# HELP ICON #}
{#            <h4><i class="activator small material-icons">info_outline</i></h4>#}
        </div>

        {# HELP_BOX #}
{#        {% include "help_box.html" %}#}
    </div>
</div>

app/templates/site/email_card_student.html
<!doctype html>
<html>
    <head>

        {# TITLE #}
        <title>Criminal Justice Institute Intake Project Student Email</title>

        {# META #}
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        {# LINKS #}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>

        <style>
            .body {
                font-family: TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif !important;
                background-color: #f6f6f6 !important;

            }
            .card {
                padding: 15px;
            }

            .card-title{
                color: black;
                border-bottom: 1px solid #C3D7A4 !important;
                box-shadow: 0 1px 0 0 #C3D7A4 !important
            }

            h6 {
                font-size: 8pt; !important
            }

        </style>

    </head>
    <body class="body">
        <div class="content-wrapper">
            <div class="container"></div>
                <div class="row">
                    <div class="col m2">
                    </div>
                    <div class="col s12 m8">
                        <div class="card">
                            <div class="card-title center-align">
                                <h1>CJI Intake Assistant</h1>
                            </div>
                            <div class="card-body">
                                <p>Hello, {{ student_name }}!</p>
                                <p>Congratulations on completing your web intake for {{ client_name }}! All of your documents for {{ client_salutation }}'s case are attached to this email. Make sure to save these documents somewhere safe!</p>
                                <p>I've also attached a calendar invite for your client's next court date.  Don't forget to invite your clinical instructor so that it will be on their calendar as well.  I sent them an email to let them know about your new case, but you should still plan on touching base with them as soon as possible.</p>
                                <p>All the best,</p>
                                <p>CJI Intake Assistant</p>
                            </div>
                        </div>
                    </div>
                    <div class="col m2">
                    </div>
                    <div class="col s12">
                        <div class="footer center-align">
                            <h6>Criminal Justice Institute @ Harvard Law School</h6>
                            <h6>6 Everett Street, 5th Floor</h6>
                            <h6>Cambridge, MA  02138</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/site/headers.html
<!DOCTYPE html>

<html >

    <head>

        {# TITLE #}
        <title>Criminal Justice Institute Intake Project</title>

        {# META #}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        {# LINKS #}
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="/static/css/materialize.css">
        <link rel="stylesheet" href="/static/css/styles.css">
        <link rel="shortcut icon" href="/static/images/favicon.ico">

        {# SCRIPTS #}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvY3K_Akeny_LbYTagXxYR6ZafAr-A_JQ&libraries=places" async defer></script>
        <script src="/static/javascript/autocomplete_lists.js"></script>
        <script src="/static/javascript/autocomplete_maps.js"></script>
        <script src="/static/javascript/auto_populate.js"></script>
        <script src="/static/javascript/updatepage_color.js"></script>
        <script src="/static/javascript/updatepage_dictionary.js"></script>
        <script src="/static/javascript/enable_buttons.js"></script>
        <script src="/static/javascript/firstcard.js"></script>
        <script src="/static/javascript/updatepage_loadmodal.js"></script>
        <script src="/static/javascript/updatepage_nextcard.js"></script>
        <script src="/static/javascript/updatepage_submitdata.js"></script>
        <script src="/static/javascript/updatepage_toast.js"></script>
        <script src="/static/javascript/updatepage.js"></script>

        {# INITIALIZATION SCRIPT #}
        <script>
            $(document).ready(function() {

                // Initialize select
                $('select').material_select();
            });
        </script>
        <style>
            body {
                font-family: TimesNewRoman, "Times New Roman", Times, Baskerville, Georgia, serif !important;
                background-color: #f6f6f6 !important;
            }

            .offcentered {
                  position: fixed;
                  top: 25%;
                  left: 50%;
                  /* bring your own prefixes */
                  transform: translate(-50%, -25%);
            }

            .card .card-title {
                font-size: 35px !important;
                font-weight: 300 !important;
                line-height: 35pt !important;
            }

            .card {
                position: relative;
                margin: 0.5rem 0 4rem 0;
                background-color: #ffffff;
                transition: box-shadow .25s;
                border-radius: 2px;
            }

            input[type=text] {
                margin: 0 0 30px 0;
            }

            .modal {
                width: 70% !important;
            }

            .modal-title {
                border-bottom: 1px solid #C3D7A4 !important;
                box-shadow: 0 1px 0 0 #C3D7A4 !important;
            }

            .row {
                margin-bottom: 0 !important;
            }

            .row .col.s3 {
                padding-top: 1rem !important;
                border-right: 2px solid #C3D7A4 !important;
                padding-bottom: 21.5px !important;
            }

            input:not([type]) {
                background-color: transparent;
                border: none;
                border-bottom: 1px solid #9e9e9e;
                border-radius: 0;
                outline: none;
                height: 2em !important;
                width: 300% !important;
                font-size: 1rem !important;
                margin: 0 0 20px 0 !important;
                padding: 0 !important;
                box-shadow: none;
                box-sizing: content-box;
                transition: all 0.3s;
            }
        </style>
    </head>

app/templates/site/help_box.html
<div class="card-reveal">
    <span class="card-title">Information:<i class="small material-icons left">cancel</i></span>
    <p class="card-content">{{ card.card_helptext }}</p>
</div>

app/templates/site/index.html
<!DOCTYPE html>
<html>
<head>
<title>Developing Justice</title>
<meta name="description" content="TBD" />
<!-- Copyright 1998-2017 by Northwoods Software Corporation. -->
<meta charset="UTF-8">
      <link href="../static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="../static/css/styles.css" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="../static/css/modifications.css" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="../static/css/index.css" type="text/css" rel="stylesheet" media="screen,projection"/>
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

      <script src="../static/javascript/go.js"></script>
      <script src="../static/javascript/postback.js"></script>
      <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
      <script src="../static/javascript/indexJs.js"></script>

</head>

<body>
<div class="zoom">
  <button class="diagramEditButton" onclick="myDiagram.commandHandler.increaseZoom(1.5)">+</button>
  <button class="diagramEditButton" onclick="myDiagram.commandHandler.decreaseZoom(0.7)">-</button>
</div>
<div id="sample">
  <div id="myDiagramDiv"></div>
  <div id="myDiagramDivButtons">
    <button class="diagramEditButton js-addQuestionButton">Add Question</button>
    <button class="diagramEditButton js-removeQuestionButton">Remove Question</button>
    <button class="diagramEditButton js-addAnswerButton">Add Answer</button>
    <button class="diagramEditButton js-removeAnswerButton">Remove Answer</button>
    <div class="ddButtonWrapper">
      <button class="diagramEditButton js-saveButton">Save &#x25BE;</button>
      <ul class="ddButton">
        <li class="diagramEditButton js-saveLocalButton">Download</li>
        <li class="diagramEditButton js-saveRemoteButton">Save to Server</li>
      </ul>
    </div>
    <div class="ddButtonWrapper">
      <button class="diagramEditButton js-loadButton">Load Template &#x25BE;</button>
      <ul class="ddButton">
        <li class="diagramEditButton js-loadContactInfo">Contact Info</li>
        <li class="diagramEditButton js-loadDemographics">Demographics</li>
        <li class="diagramEditButton js-loadEnd">End of Intake</li>
      </ul>
    </div>
    <button class="diagramEditButton js-layoutButton">Fix Layout</button>
  </div>
  <div id="preview">
    <div class="js-previewNoCard"> Click on a card above to edit it here.</div>
    <div class="container js-previewContainer">
      {% include 'card.html' %}
    </div>
  </div>
  <div id="previewVariables">
    Variables listed here.
  </div>
  <br>

  <textarea id="mySavedModel">
    {{currModel}}
  </textarea>

  </div>
</div>
</body>
</html>

app/templates/site/layout.html
{% include "site/headers.html" %}
{% include "site/nav.html" %}
{% include "site/splash.html" %}
{% include "site/modal.html" %}
<div class="content-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            {% block content %}
                {% for card in cardlist %}
                    {% include "site/card_type.html" %}
                {% endfor %}
            {% endblock %}
            {% include "site/submitted_card.html" %}
            {% include "site/error_card.html" %}
            {% include "site/loader_card.html" %}
        </div>
    </div>
</div>

app/templates/site/loader_card.html
<div class="col s12" id="LOADER_CARD" style="Display: None; margin-top: 10%">
    <div class="card">
        <div class="card-content center-align">
            <div class="card-title">
                <h4>Please Wait One Moment While I Process Your Information</h4>
            </div><br>
            <div class="progress">
                <div class="indeterminate"></div>
            </div><br>
        </div>
    </div>
</div>

app/templates/site/modal.html
<div id="modal" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div class="row">
            <div class="col s12 center modal-title">
                <h3>Would you like to submit the following information?</h3>
            </div>
        </div>
        {% block content %}
            {% for card in cardlist %}
                <div class="row" {% if loop.index0 % 2 == 0 %} style="background-color: #f4f4f4" {% endif %}>
                    <div class="col s1"></div>
                    <div class="col s3">
                        <h6>{{ card.card_subtext }}</h6>
                    </div>
                    <div class="col s1"></div>
                    <div class="col s7">
                        <i class="material-icons prefix tiny">{{ card.card_icon }}</i>
                        <div class="input-field inline">
                            <input id="{{ card.card_id }}_MODAL">
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endblock %}
    </div>
    <div class="modal-footer">
        <a onclick="submitdata()" class="modal-action modal-close waves-effect waves-white btn-flat">Submit</a>
        <a onclick="" class="modal-action modal-close waves-effect waves-white btn-flat">Cancel</a>
    </div>
</div>

app/templates/site/nav.html
<body>

    {# NAV HEADER #}
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper white">
                <a class="brand-logo left" style="width: 20%; min-width: 240pt"><img src="/static/images/developing_justice.png" style="width: 20%; min-width: 240pt; padding: 5pt"></a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                      {% if current_user.is_admin %}
                          <li><a class="ink-text" href="{{ url_for('site.admin', site_url_slug=g.site.site_url_slug) }}">Admin</a></li>
                          <li><a class="ink-text" href=".">Reset Form</a></li>
                      {% else %}
                          <li><a class="ink-text" href=".">Reset Form</a></li>
                      {% endif %}
                </ul>
            </div>
        </nav>
    </div>

app/templates/site/submitted_card.html
{# SUBMITTED CARD #}
<div class="col s12" id="SUBMITTED_CARD" style="display: None; margin-top: 10%">
    <div class="card">
        <div class="card-content">
            <h4 class="card-title center-align">Congratulations!</h4>
            <h4 class="card-title center-align">Your information has been submitted successfully&mdash;check your email!</h4><br>
            <p class="center-align"><a class="waves-effect waves-light btn-large" id="start_button" href=".">Click Here To Conduct An Intake For Another Client</a></p>
        </div>
    </div>
</div>